---
- name: install magicmirror on Rpi
  hosts: magicmirror
  vars:
  roles:
    - common
    - magicmirror
  tasks:
  - name: Show all the hosts in the inventory
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ groups['all'] }}"

  - name: Show all the hosts in the current play
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ ansible_play_batch }}"

  