---
# DELETE First
  - name: delete host specific cronjobs
    ansible.builtin.cron:
      "{{item | combine ({'state' : 'absent'}) }}"
    loop:
      "{{ hostc.crontabs }}"
    when:
      - hostc is defined
      - hostc.crontabs is defined

  - name: delete group specific cronjobs
    # source ./group_vars/<groupname>/crontabs.yaml
    ansible.builtin.cron:
      "{{item | combine ({'state' : 'absent'}) }}"
    with_items: "{{ group.crontabs }}"
    when:
      - group is defined
      - group.crontabs is defined

# ADD Second
  - name: add host specific cronjobs
    # source ./hosts_vars/<hostname>/crontabs.yaml
    ansible.builtin.cron:
      "{{item}}"
    loop:
      "{{ hostc.crontabs }}"
    when:
      - hostc is defined
      - hostc.crontabs is defined

  - name: add group specific cronjobs
    # source ./group_vars/<groupname>/crontabs.yaml
    ansible.builtin.cron:
      "{{item}}"
    with_items: "{{ group.crontabs }}"
    when:
      - group is defined
      - group.crontabs is defined