---

- name: "Download Module {{ item.name }}"
  git:
    repo: "{{ item.github }}"
    dest: "{{ mm_root }}/modules/{{ item.name }}"
    force: yes

- name: "NPM Install Module {{ item.name }}"
  npm:
    path: "{{ mm_root }}/modules/{{ item.name }}"
  ignore_errors: yes