---
  - name: uninstall unnecessary stuff
    become: true
    apt:
      pkg:
        - wolfram-engine
        - scratch
        - scratch2
        - nuscratch
        - sonic-pi
        - idle3
        - smartsim
        - ava-common
        - minecraft-pi
        - libreoffice*
      state: "absent"
      autoclean: true
      autoremove: true

  - name: apt Update
    become: true
    ansible.builtin.apt:
      update_cache: yes

  - name: Upgrade the OS (apt-get dist-upgrade)
    become: true
    ansible.builtin.apt:
      upgrade: dist

  - name: apt upgrade
    become: true
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: install packages
    become: true
    ansible.builtin.apt:
      pkg:
        - python3
        - python3-pip
        - git
        - python3-dev
        - sshpass
        - mpg321
        - alsa-utils