---
  - name: be sure ntp is installed
    apt:
      name: ntp
      state: present

  - name: be sure ntp is configured
    template:
      src: ntp.conf.j2
      dest: /etc/ntp.conf
    notify:
      - restart ntpd
      # see the handlers folder

  - name: be sure ntpd is running and enabled
    service:
      name: ntpd
      state: started
      enabled: yes